#!/usr/bin/env python3
"""
01_data_inspection.py
======================
Phase 1 & 2: Inspect raw hydrated data.
Produces:
  - Documentation/data_dictionary.md
  - Analysis/data_quality_report.csv
"""

import csv
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW  = ROOT / "Raw"
DOCS = ROOT / "Documentation"
ANALYSIS = ROOT / "Analysis"

DOCS.mkdir(exist_ok=True)
ANALYSIS.mkdir(exist_ok=True)

MASTER = RAW / "master_table_hydrated.csv"
VIDEOS = RAW / "hydrated_videos.csv"

# ── LOAD ─────────────────────────────────────────────────────────────────────
print("[01] Loading raw files...")
with open(MASTER, newline="", encoding="utf-8-sig") as f:
    master_rows = list(csv.DictReader(f))
    master_cols = list(master_rows[0].keys()) if master_rows else []

with open(VIDEOS, newline="", encoding="utf-8-sig") as f:
    video_rows = list(csv.DictReader(f))
    video_cols = list(video_rows[0].keys()) if video_rows else []

print(f"  master_table_hydrated.csv: {len(master_rows)} rows, {len(master_cols)} cols")
print(f"  hydrated_videos.csv:       {len(video_rows)} rows, {len(video_cols)} cols")

# ── QUALITY CHECKS ───────────────────────────────────────────────────────────
quality_rows = []

def check_column(rows, col, label):
    total = len(rows)
    missing  = sum(1 for r in rows if not r.get(col, "").strip())
    unique   = len(set(r.get(col,"").strip() for r in rows if r.get(col,"").strip()))
    sample   = next((r[col] for r in rows if r.get(col,"").strip()), "")[:80]
    return {
        "file": label,
        "column": col,
        "total_rows": total,
        "missing": missing,
        "missing_pct": round(missing/total*100, 1),
        "unique_values": unique,
        "sample_value": sample,
    }

for col in master_cols:
    quality_rows.append(check_column(master_rows, col, "master_table_hydrated"))

for col in video_cols:
    quality_rows.append(check_column(video_rows, col, "hydrated_videos"))

# Duplicate video IDs in master
master_ids = [r["Video ID"].strip() for r in master_rows if r.get("Video ID","").strip()]
dup_ids = len(master_ids) - len(set(master_ids))
print(f"\n  Duplicate Video IDs in master (expected — same video in multiple playlists): {dup_ids}")
print(f"  Unique Video IDs in master: {len(set(master_ids))}")

# Status breakdown
statuses = Counter(r.get("Status","").strip() for r in master_rows)
print(f"\n  Status breakdown:")
for k,v in statuses.most_common():
    print(f"    {k or '[blank]'}: {v}")

# Duration format check
iso_re = re.compile(r"^PT(\d+H)?(\d+M)?(\d+S)?$")
bad_dur = [r for r in master_rows if r.get("Duration","").strip() and not iso_re.match(r["Duration"].strip())]
print(f"\n  Malformed Duration values: {len(bad_dur)}")

# Date format check
date_re = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}")
bad_ts = [r for r in master_rows if r.get("Added Timestamp","").strip() and not date_re.match(r["Added Timestamp"].strip())]
print(f"  Malformed Added Timestamp values: {len(bad_ts)}")

# Year range
years = sorted(set(r.get("Year","").strip() for r in master_rows if r.get("Year","").strip().isdigit()))
print(f"  Year range: {years[0]} – {years[-1]}" if years else "  No years found")

# Save quality report
with open(ANALYSIS / "data_quality_report.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["file","column","total_rows","missing",
                                           "missing_pct","unique_values","sample_value"])
    writer.writeheader()
    writer.writerows(quality_rows)
print(f"\n  Saved: Analysis/data_quality_report.csv")

# ── DATA DICTIONARY ──────────────────────────────────────────────────────────
dd = """# Data Dictionary

Generated by `01_data_inspection.py`.

---

## master_table_hydrated.csv

| Column | Type | Source | Notes |
|---|---|---|---|
| Video ID | string | YouTube Takeout | YouTube video identifier. Not unique per row — same ID may appear in multiple playlists. |
| Playlist | string | YouTube Takeout | Name of the playlist this entry was saved to. |
| Added Timestamp | datetime (ISO 8601) | YouTube Takeout | When the video was added to the playlist. UTC timezone. |
| Year | integer | Takeout (derived) | Year portion of Added Timestamp. |
| Topic Category | string | Derived (script) | Broad category assigned during master table construction. |
| Life Phase | string | Derived (script) | Life phase label mapped to timestamp range. |
| YouTube URL | string | Derived | Full watch URL. |
| Title | string | YouTube Data API v3 | Video title at time of hydration. Empty if unavailable. |
| Channel Name | string | YouTube Data API v3 | Channel display name. |
| Channel ID | string | YouTube Data API v3 | Unique channel identifier (UC…). |
| Published At | datetime (ISO 8601) | YouTube Data API v3 | When the video was originally published. |
| Category ID | integer | YouTube Data API v3 | YouTube's numeric category identifier. |
| Category | string | YouTube Data API v3 | YouTube's category label (e.g. Education, Sports). |
| Duration | string (ISO 8601) | YouTube Data API v3 | Video duration (e.g. PT1H02M03S). |
| Duration Seconds | integer | YouTube Data API v3 | Duration converted to total seconds. |
| View Count | integer | YouTube Data API v3 | View count at time of hydration. |
| Like Count | integer | YouTube Data API v3 | Like count at time of hydration. May be hidden by creator. |
| Tags | string (pipe-separated) | YouTube Data API v3 | Creator-supplied tags. Many videos have none. |
| Status | string | YouTube Data API v3 | `found` = active. `unavailable` = deleted/private/restricted. |

---

## hydrated_videos.csv

| Column | Type | Source | Notes |
|---|---|---|---|
| video_id | string | YouTube Takeout | Unique video identifier. One row per unique ID. |
| title | string | YouTube Data API v3 | Video title. |
| channel_name | string | YouTube Data API v3 | Channel display name. |
| channel_id | string | YouTube Data API v3 | Unique channel identifier. |
| published_at | datetime (ISO 8601) | YouTube Data API v3 | Publication date. |
| category_id | integer | YouTube Data API v3 | Numeric category ID. |
| category | string | YouTube Data API v3 | Category label. |
| default_language | string | YouTube Data API v3 | Video language if declared by creator. Often blank. |
| duration | string (ISO 8601) | YouTube Data API v3 | Raw ISO 8601 duration string. |
| duration_seconds | integer | YouTube Data API v3 | Duration in seconds. |
| view_count | integer | YouTube Data API v3 | View count at hydration time. |
| like_count | integer | YouTube Data API v3 | Like count at hydration time. |
| tags | string (pipe-separated) | YouTube Data API v3 | Creator tags. |
| description | string | YouTube Data API v3 | First 300 characters of description. |
| status | string | YouTube Data API v3 | `found` or `unavailable`. |
| youtube_url | string | Derived | Full watch URL. |

---

## Known Data Quality Issues

| Issue | Detail |
|---|---|
| Tags missing | ~30% of videos have no tags. Classification relies on title and channel when tags are absent. |
| Like Count missing | ~13% of videos have no like count. YouTube allows creators to hide likes. |
| Deleted/private videos | 384 unique IDs (13.5%) returned unavailable. Content unrecoverable. |
| Duplicate rows | The master table contains one row per playlist entry, not one per video. The same video may appear in multiple playlists. |
| Duration of zero | A small number of entries (live streams, premieres) may have zero or missing duration. |
| Year column | Pre-computed in the takeout pipeline. Cross-checked against Added Timestamp during cleaning. |
"""

with open(DOCS / "data_dictionary.md", "w", encoding="utf-8") as f:
    f.write(dd)
print("  Saved: Documentation/data_dictionary.md")
print("\n[01] DONE")
